# Keras Basics

## Data Preprocessing

In [1]:
import numpy as np 
from numpy import genfromtxt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import confusion_matrix, classification_report
from keras.models import load_model

Using TensorFlow backend.


In [2]:
data = genfromtxt('../DATA/bank_note_data.txt', delimiter=',')

In [3]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [4]:
labels = data[:, -1]

In [5]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [6]:
features = data[:, 0:4]

In [7]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [8]:
X = features

y = labels

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [10]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [11]:
len(X_train)

919

In [12]:
X

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [13]:
len(X)

1372

In [14]:
len(X_test)

453

In [15]:
X_test

array([[ 1.5691  ,  6.3465  , -0.1828  , -2.4099  ],
       [-0.27802 ,  8.1881  , -3.1338  , -2.5276  ],
       [ 0.051979,  7.0521  , -2.0541  , -3.1508  ],
       ...,
       [ 3.5127  ,  2.9073  ,  1.0579  ,  0.40774 ],
       [ 5.504   , 10.3671  , -4.413   , -4.0211  ],
       [-0.2062  ,  9.2207  , -3.7044  , -6.8103  ]])

In [16]:
y_train

array([1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 0.,
       1., 1., 1., 0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0.,
       1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1.,
       1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1.,
       0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0.,
       1., 0., 0., 1., 0.

In [17]:
y_test

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1.,
       1., 0., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0.,
       0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       0., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1.,
       1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
       1., 1., 0., 1., 0.

In [18]:
scaler_object = MinMaxScaler() 

In [19]:
X_train.min(), X_train.argmin(), X_train.max(), X_train.argmax()

(-13.7731, 1113, 17.9274, 1114)

In [20]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [21]:
scaled_X_train = scaler_object.transform(X_train)

In [22]:
scaled_X_test = scaler_object.transform(X_test)

In [23]:
scaled_X_train.min(), scaled_X_train.argmin(), scaled_X_train.max(), scaled_X_train.argmax()

(0.0, 348, 1.0000000000000002, 1114)

In [24]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [25]:
scaled_X_train

array([[4.44850688e-01, 5.14130449e-01, 2.18194638e-01, 8.50172258e-01],
       [6.53339968e-01, 5.82655745e-01, 9.93242398e-02, 8.17696322e-01],
       [4.81846700e-01, 6.69377018e-01, 3.61193167e-01, 7.63368407e-01],
       ...,
       [4.11050776e-04, 8.63104170e-01, 2.34046756e-01, 3.74261253e-01],
       [2.58284115e-01, 6.16029366e-01, 2.33861752e-01, 7.02643151e-01],
       [2.65661395e-01, 2.44444278e-01, 7.20316361e-01, 7.44775785e-01]])

## Building the Model

In [26]:
from keras.models import Sequential
from keras.layers import Dense

In [27]:
model = Sequential()

model.add(Dense(X_train.shape[1], input_dim=X_train.shape[1], activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [28]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [29]:
model.fit(scaled_X_train, y_train, epochs=50, verbose=2)

Epoch 1/50
 - 0s - loss: 0.8125 - acc: 0.4494
Epoch 2/50
 - 0s - loss: 0.7601 - acc: 0.4037
Epoch 3/50
 - 0s - loss: 0.7307 - acc: 0.2546
Epoch 4/50
 - 0s - loss: 0.7092 - acc: 0.3819
Epoch 5/50
 - 0s - loss: 0.6920 - acc: 0.5593
Epoch 6/50
 - 0s - loss: 0.6724 - acc: 0.5724
Epoch 7/50
 - 0s - loss: 0.6544 - acc: 0.6344
Epoch 8/50
 - 0s - loss: 0.6253 - acc: 0.6768
Epoch 9/50
 - 0s - loss: 0.5957 - acc: 0.7214
Epoch 10/50
 - 0s - loss: 0.5669 - acc: 0.7987
Epoch 11/50
 - 0s - loss: 0.5414 - acc: 0.8205
Epoch 12/50
 - 0s - loss: 0.5176 - acc: 0.8292
Epoch 13/50
 - 0s - loss: 0.4960 - acc: 0.8487
Epoch 14/50
 - 0s - loss: 0.4754 - acc: 0.8542
Epoch 15/50
 - 0s - loss: 0.4585 - acc: 0.8553
Epoch 16/50
 - 0s - loss: 0.4414 - acc: 0.8564
Epoch 17/50
 - 0s - loss: 0.4261 - acc: 0.8575
Epoch 18/50
 - 0s - loss: 0.4127 - acc: 0.8629
Epoch 19/50
 - 0s - loss: 0.3998 - acc: 0.8683
Epoch 20/50
 - 0s - loss: 0.3880 - acc: 0.8716
Epoch 21/50
 - 0s - loss: 0.3768 - acc: 0.8760
Epoch 22/50
 - 0s - lo

In [30]:
predictions = model.predict_classes(scaled_X_test)

predictions[:10]

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]], dtype=int32)

In [31]:
model.metrics_names

['loss', 'acc']

In [32]:
confusion_matrix(y_test, predictions)

array([[252,   5],
       [ 19, 177]])

In [33]:
print(classification_report(y_test, predictions))

             precision    recall  f1-score   support

        0.0       0.93      0.98      0.95       257
        1.0       0.97      0.90      0.94       196

avg / total       0.95      0.95      0.95       453



In [34]:
model.save('my_model.h5')

In [35]:
new_model = load_model('my_model.h5')

In [36]:
new_model.predict_classes(scaled_X_test)[:10]

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]], dtype=int32)